// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqClientHost struct {
	AppVersion           string   `protobuf:"bytes,1,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqClientHost) Reset()         { *m = ReqClientHost{} }
func (m *ReqClientHost) String() string { return proto.CompactTextString(m) }
func (*ReqClientHost) ProtoMessage()    {}
func (*ReqClientHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ReqClientHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqClientHost.Unmarshal(m, b)
}
func (m *ReqClientHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqClientHost.Marshal(b, m, deterministic)
}
func (m *ReqClientHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqClientHost.Merge(m, src)
}
func (m *ReqClientHost) XXX_Size() int {
	return xxx_messageInfo_ReqClientHost.Size(m)
}
func (m *ReqClientHost) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqClientHost.DiscardUnknown(m)
}

var xxx_messageInfo_ReqClientHost proto.InternalMessageInfo

func (m *ReqClientHost) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *ReqClientHost) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type ClientHost struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHost) Reset()         { *m = ClientHost{} }
func (m *ClientHost) String() string { return proto.CompactTextString(m) }
func (*ClientHost) ProtoMessage()    {}
func (*ClientHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ClientHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHost.Unmarshal(m, b)
}
func (m *ClientHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHost.Marshal(b, m, deterministic)
}
func (m *ClientHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHost.Merge(m, src)
}
func (m *ClientHost) XXX_Size() int {
	return xxx_messageInfo_ClientHost.Size(m)
}
func (m *ClientHost) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHost.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHost proto.InternalMessageInfo

func (m *ClientHost) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ClientHost) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *ClientHost) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ClientHost) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RespClientHost struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Host                 []*ClientHost `protobuf:"bytes,3,rep,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RespClientHost) Reset()         { *m = RespClientHost{} }
func (m *RespClientHost) String() string { return proto.CompactTextString(m) }
func (*RespClientHost) ProtoMessage()    {}
func (*RespClientHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RespClientHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespClientHost.Unmarshal(m, b)
}
func (m *RespClientHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespClientHost.Marshal(b, m, deterministic)
}
func (m *RespClientHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespClientHost.Merge(m, src)
}
func (m *RespClientHost) XXX_Size() int {
	return xxx_messageInfo_RespClientHost.Size(m)
}
func (m *RespClientHost) XXX_DiscardUnknown() {
	xxx_messageInfo_RespClientHost.DiscardUnknown(m)
}

var xxx_messageInfo_RespClientHost proto.InternalMessageInfo

func (m *RespClientHost) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespClientHost) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RespClientHost) GetHost() []*ClientHost {
	if m != nil {
		return m.Host
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqClientHost)(nil), "proto.ReqClientHost")
	proto.RegisterType((*ClientHost)(nil), "proto.ClientHost")
	proto.RegisterType((*RespClientHost)(nil), "proto.RespClientHost")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x3d, 0x4b, 0x03, 0x41,
	0x10, 0x35, 0x77, 0x1b, 0x3f, 0x9e, 0x18, 0x70, 0x50, 0x58, 0x52, 0x48, 0x38, 0x10, 0x52, 0xa5,
	0x88, 0x58, 0x5a, 0xd9, 0x68, 0x63, 0xb1, 0x85, 0x95, 0xcd, 0xe9, 0x0d, 0xba, 0x60, 0x6e, 0xc7,
	0xdd, 0xf5, 0xff, 0xcb, 0x8d, 0xe7, 0xb9, 0xa9, 0x66, 0xde, 0x9b, 0x8f, 0xf7, 0x78, 0xc0, 0x77,
	0xe2, 0xb8, 0x91, 0x18, 0x72, 0xa0, 0xb9, 0x96, 0xe6, 0x11, 0x67, 0x8e, 0xbf, 0xee, 0x3f, 0x3d,
	0xf7, 0xf9, 0x21, 0xa4, 0x4c, 0x57, 0x40, 0x2b, 0xf2, 0xcc, 0x31, 0xf9, 0xd0, 0xdb, 0xd9, 0x6a,
	0xb6, 0x3e, 0x71, 0x05, 0x43, 0x16, 0x47, 0xad, 0xc8, 0x53, 0xbb, 0x63, 0x5b, 0xe9, 0xf0, 0x0f,
	0x36, 0x2f, 0x40, 0xf1, 0x67, 0x81, 0xca, 0x77, 0x7a, 0x3f, 0x77, 0x95, 0xef, 0x68, 0x89, 0xe3,
	0x8f, 0x90, 0x72, 0x71, 0x38, 0x61, 0xdd, 0x15, 0x5b, 0x2b, 0x5b, 0x79, 0x21, 0x82, 0x91, 0x10,
	0xb3, 0x35, 0xca, 0x68, 0xdf, 0x30, 0x16, 0x8e, 0x93, 0x14, 0x0a, 0x04, 0xf3, 0x16, 0x3a, 0x1e,
	0x35, 0xb4, 0x1f, 0xdc, 0xed, 0x38, 0xa5, 0xf6, 0x7d, 0x72, 0x37, 0x42, 0xba, 0x86, 0x19, 0xf4,
	0x6c, 0xbd, 0xaa, 0xd7, 0xa7, 0xdb, 0xf3, 0xdf, 0x14, 0x36, 0xff, 0xef, 0x9c, 0x8e, 0xb7, 0x77,
	0x30, 0x43, 0x48, 0x74, 0x0b, 0xa3, 0x22, 0x17, 0xe3, 0xe2, 0x5e, 0x48, 0xcb, 0xcb, 0x89, 0x2d,
	0x1d, 0x35, 0x07, 0xaf, 0x87, 0xca, 0xdf, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xa9, 0x79,
	0xf3, 0x6a, 0x01, 0x00, 0x00,
}
