// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: db.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Db service

type DbService interface {
	// 获取游戏服务器
	GetHost(ctx context.Context, in *ReqHost, opts ...client.CallOption) (*RespHost, error)
}

type dbService struct {
	c    client.Client
	name string
}

func NewDbService(name string, c client.Client) DbService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &dbService{
		c:    c,
		name: name,
	}
}

func (c *dbService) GetHost(ctx context.Context, in *ReqHost, opts ...client.CallOption) (*RespHost, error) {
	req := c.c.NewRequest(c.name, "Db.GetHost", in)
	out := new(RespHost)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Db service

type DbHandler interface {
	// 获取游戏服务器
	GetHost(context.Context, *ReqHost, *RespHost) error
}

func RegisterDbHandler(s server.Server, hdlr DbHandler, opts ...server.HandlerOption) error {
	type db interface {
		GetHost(ctx context.Context, in *ReqHost, out *RespHost) error
	}
	type Db struct {
		db
	}
	h := &dbHandler{hdlr}
	return s.Handle(s.NewHandler(&Db{h}, opts...))
}

type dbHandler struct {
	DbHandler
}

func (h *dbHandler) GetHost(ctx context.Context, in *ReqHost, out *RespHost) error {
	return h.DbHandler.GetHost(ctx, in, out)
}
