// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqHost struct {
	HostName             string   `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHost) Reset()         { *m = ReqHost{} }
func (m *ReqHost) String() string { return proto.CompactTextString(m) }
func (*ReqHost) ProtoMessage()    {}
func (*ReqHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *ReqHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHost.Unmarshal(m, b)
}
func (m *ReqHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHost.Marshal(b, m, deterministic)
}
func (m *ReqHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHost.Merge(m, src)
}
func (m *ReqHost) XXX_Size() int {
	return xxx_messageInfo_ReqHost.Size(m)
}
func (m *ReqHost) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHost.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHost proto.InternalMessageInfo

func (m *ReqHost) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

type Host struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Host) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Host) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Host) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RespHost struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Host                 []*Host  `protobuf:"bytes,3,rep,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespHost) Reset()         { *m = RespHost{} }
func (m *RespHost) String() string { return proto.CompactTextString(m) }
func (*RespHost) ProtoMessage()    {}
func (*RespHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *RespHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespHost.Unmarshal(m, b)
}
func (m *RespHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespHost.Marshal(b, m, deterministic)
}
func (m *RespHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespHost.Merge(m, src)
}
func (m *RespHost) XXX_Size() int {
	return xxx_messageInfo_RespHost.Size(m)
}
func (m *RespHost) XXX_DiscardUnknown() {
	xxx_messageInfo_RespHost.DiscardUnknown(m)
}

var xxx_messageInfo_RespHost proto.InternalMessageInfo

func (m *RespHost) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespHost) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RespHost) GetHost() []*Host {
	if m != nil {
		return m.Host
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqHost)(nil), "proto.ReqHost")
	proto.RegisterType((*Host)(nil), "proto.Host")
	proto.RegisterType((*RespHost)(nil), "proto.RespHost")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4f, 0x8b, 0x83, 0x30,
	0x10, 0xc5, 0xd7, 0x18, 0x57, 0x77, 0x84, 0x5d, 0x98, 0x53, 0xf0, 0xb2, 0x12, 0x58, 0xf0, 0xb0,
	0x78, 0xb0, 0x5f, 0xa1, 0xd0, 0x9e, 0x7a, 0xc8, 0xa1, 0xd0, 0xa3, 0x36, 0xa1, 0xf5, 0x20, 0x49,
	0x4d, 0xbe, 0x3f, 0xc5, 0xf1, 0x0f, 0x78, 0xca, 0xbc, 0x37, 0x6f, 0x7e, 0x99, 0x81, 0x4c, 0x77,
	0xb5, 0x1b, 0x6d, 0xb0, 0x98, 0xd0, 0x23, 0xff, 0x20, 0x55, 0xe6, 0x75, 0xb6, 0x3e, 0x60, 0x01,
	0xd9, 0xd3, 0xfa, 0x70, 0x69, 0x07, 0x23, 0xa2, 0x32, 0xaa, 0xbe, 0xd4, 0xa6, 0xe5, 0x15, 0x38,
	0x65, 0xbe, 0x81, 0xf5, 0x9a, 0xba, 0x89, 0x62, 0xbd, 0xde, 0xcd, 0xb0, 0xfd, 0x0c, 0x65, 0x9d,
	0x88, 0xc9, 0x65, 0xbd, 0x43, 0x04, 0xee, 0xec, 0x18, 0x04, 0x27, 0x87, 0x6a, 0x79, 0x83, 0x4c,
	0x19, 0xef, 0x88, 0x8d, 0xc0, 0xef, 0x56, 0x9b, 0x85, 0x4e, 0x35, 0x0a, 0x48, 0x07, 0xe3, 0x7d,
	0xfb, 0x58, 0xf1, 0xab, 0xc4, 0x5f, 0xe0, 0xd3, 0x4f, 0x22, 0x2e, 0xe3, 0x2a, 0x6f, 0xf2, 0xf9,
	0xaa, 0x7a, 0x02, 0x29, 0x6a, 0x34, 0x0d, 0xb0, 0x63, 0x87, 0xff, 0x90, 0x9e, 0x4c, 0x98, 0x77,
	0x5f, 0x32, 0xcb, 0xbd, 0xc5, 0xcf, 0xa6, 0xe7, 0x05, 0xe4, 0x47, 0xf7, 0x49, 0xce, 0xe1, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xac, 0xf0, 0xee, 0x67, 0x27, 0x01, 0x00, 0x00,
}
